overage:
    status:
        project:
            default:
                threshold: 0.01%
            proxy-graphql:
                flags: proxy-graphql
        patch: off
flags:
    proxy-graphql:
        paths:
            - services/proxy-graphql/src
