stages:
    - .pre
    - build
    - deploy

variables:
    DEV_ENVIRONMENT_IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/dev-environment:latest
Prepare:
    stage: .pre
    only:
        changes:
            - .dev-env.Dockerfile
    interruptible: true
    tags:
        - docker
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker pull $DEV_ENVIRONMENT_IMAGE_TAG || true
        - docker build --cache-from $DEV_ENVIRONMENT_IMAGE_TAG -t $DEV_ENVIRONMENT_IMAGE_TAG --file .dev-env.Dockerfile .
        - docker push $DEV_ENVIRONMENT_IMAGE_TAG

Build:
    stage: build
    needs: []
    interruptible: true
    tags:
        - docker
    image: $DEV_ENVIRONMENT_IMAGE_TAG
    variables:
        GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
        FIREBASE_CONFIG: ${FIREBASE_CONFIG}
        DIGITALOCEAN_TOKEN: ${DIGITALOCEAN_TOKEN}
        GIT_TOKEN: ${CI_TOKEN}
        GIT_USER: ${GITLAB_USER_EMAIL}
    script:
        - yarn
        - feuertiger init
        - feuertiger build
        - feuertiger lint
        - feuertiger test
        - feuertiger publish
        - feuertiger dockerize

#######################################################
# Deploy firebase functions                           #
# - triggered by pushes on deploy branches made by ci #
#######################################################
Deploy:
    stage: deploy
    needs: ['Build']
    only:
        refs:
            - dev
    interruptible: true
    tags:
        - docker
    image: $DEV_ENVIRONMENT_IMAGE_TAG
    variables:
        GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
        FIREBASE_CONFIG: ${FIREBASE_CONFIG}
        DIGITALOCEAN_TOKEN: ${DIGITALOCEAN_TOKEN}
        GIT_TOKEN: ${CI_TOKEN}
        GIT_USER: ${GITLAB_USER_EMAIL}
        PULUMI_ACCESS_TOKEN: ${PULUMI_ACCESS_TOKEN}
    script:
        - yarn
