stages:
    - Prepare
    - Check
#     - Test
#     - Publish
#     - Deploy

# variables:
#   DEV_ENVIRONMENT_IMAGE_TAG: $CI_REGISTRY/feuertiger/feuertiger/dev-environment:latest

# .job-base:
#   interruptible: true


# .docker-linux-runner:
#   tags:
#     - docker

# .docker-in-docker:
#   extends:
#     - .docker-linux-runner
#   image: docker:latest
#   services:
#     - docker:dind
#   before_script:
#     - docker info
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

include:
  - local: '/.ci/0-prepare.yml'
  - local: '/.ci/1-check.yml'
#   - local: '/.ci/1-format.yml'
#   - local: '/.ci/1-test.yml'
#   - local: '/.ci/2-publish.yml'
#   - local: '/.ci/3-deploy.yml'
