stages:
    - Prepare
    - Check
    - Trigger

variables:
    DEV_ENVIRONMENT_IMAGE_TAG: $CI_REGISTRY/feuertiger/feuertiger/dev-environment:latest

Prepare:
    stage: Prepare
    interruptible: true
    tags:
        - docker
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker info
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    only:
        changes:
            - .dev-env.Dockerfile
    script:
        - docker pull $DEV_ENVIRONMENT_IMAGE_TAG || true
        - docker build --cache-from $DEV_ENVIRONMENT_IMAGE_TAG -t $DEV_ENVIRONMENT_IMAGE_TAG --file .dev-env.Dockerfile .
        - docker push $DEV_ENVIRONMENT_IMAGE_TAG

Check:
    stage: Check
    interruptible: true
    tags:
        - docker
    image: $DEV_ENVIRONMENT_IMAGE_TAG
    cache:
        key: '$CI_JOB_NAME-$CI_COMMIT_REF_SLUG'
    script:
        - yarn
        - node .ci/check.js
    artifacts:
        paths:
            - .ci/build.yml

Trigger:
    stage: Trigger
    rules:
        - exists:
              - .ci/build.yml
    trigger:
        include:
            - artifact: .ci/build.yml
              job: Check
