name: Continuous Integration

on:
    repository_dispatch:
        types: [build]

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PRIVATE_TOKEN }}
                  fetch-depth: 0
            - uses: actions/setup-node@v1
              with:
                  node-version: '13.x'
            - uses: bahmutov/npm-install@v1
            - name: Build
              env:
                  FIREBASE_SECRETS_APP_APIKEY: ${{ secrets.FIREBASE_SECRETS_APP_APIKEY }}
                  GRAB_TOKEN_TO_BREAK_LOOP: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  yarn run link
                  yarn run build
            - name: Publish
              run: |
                  git config --global user.name 'robotiger'
                  git config --global user.email 'robotiger@users.noreply.github.com'
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
                  yarn run publish
    dispatch_deploy:
        needs: build_and_publish
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev'
        runs-on: ubuntu-latest
        steps:
            - name: Repository Dispatch
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.PRIVATE_TOKEN }}
                  repository: feuertiger/feuertiger
                  event-type: deploy
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
