name: CI

on: [push]

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2-beta
            - run: |
                  git config --global user.name 'feuertiger'
                  git config --global user.email 'feuertiger@users.noreply.github.com'
            - uses: actions/setup-node@v1
              with:
                  node-version: '13.x'
            - uses: bahmutov/npm-install@v1
            - name: Build
              env:
                  FIREBASE_SECRETS_APP_APIKEY: ${{ secrets.FIREBASE_SECRETS_APP_APIKEY }}
              run: |
                  yarn run link
                  yarn run build
            - name: Publish
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
                  yarn run publish
                  git commit -am "published packages"
            - name: Temporarily disable "include administrators" branch protection
              uses: benjefferies/branch-protection-bot@master
              if: always()
              with:
                  access-token: ${{ secrets.PRIVATE_TOKEN }}
                  branch: ${GITHUB_REF##*/}
            - name: Push
              run: |
                  git push --force
            - name: Enable "include administrators" branch protection
              uses: benjefferies/branch-protection-bot@master
              if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
              with:
                  access-token: ${{ secrets.PRIVATE_TOKEN }}
                  branch: ${GITHUB_REF##*/}
                  
    deploy_firebase:
        needs: build_and_publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2-beta
            - uses: actions/setup-node@v1
              with:
                  node-version: '13.x'
            - name: Install
              working-directory: ./deployments/firebase
              run: npm install
            - name: Build
              working-directory: ./deployments/firebase
              run: npm run build
            - name: Deploy
              working-directory: ./deployments/firebase
              run: npm run deploy
