name: CI

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - uses: bahmutov/npm-install@v1
    - run: yarn run link
    - name: build
      env:
        FIREBASE_SECRETS_APP_APIKEY: ${{ secrets.FIREBASE_SECRETS_APP_APIKEY }}
      run: yarn run build 
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: repository
        path: ./
  publish:
    runs-on: ubuntu-latest
    needs: [build]    
    steps:
    - name: Download
      uses: actions/download-artifact@v1
      with:
        name: repository
    - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
    - run: yarn run version:canary
    - run: yarn run publish     
       
