name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install
      run: yarn
    - name: Bootstrap
      run: lerna bootstrap
    - name: Build
      run: lerna run build
