name: CI

on: [push]

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git checkout "${GITHUB_REF:11}"
            - uses: actions/setup-node@v1
              with:
                  node-version: '13.x'
            - uses: bahmutov/npm-install@v1
            - name: Build
              env:
                  FIREBASE_SECRETS_APP_APIKEY: ${{ secrets.FIREBASE_SECRETS_APP_APIKEY }}
              run: |
                  yarn run link
                  yarn run build
            - name: Publish
              run: |
                  echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
                  yarn run publish
                  git add .
                  git commit -m "published packaged" -a
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  force: true
                  branch: ${{ GITHUB_REF:11 }}
