name: Continuous Delivery

on:
    repository_dispatch:
        branch:
            - master
            - dev
        types: [deploy]

jobs:
    deploy_firebase:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '8'
                  registry-url: 'https://npm.pkg.github.com'
            - name: Install
              working-directory: ./deployments/firebase/functions
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npm install
            - name: Build
              working-directory: ./deployments/firebase/functions
              run: npm run build
            - name: Deploy
              working-directory: ./deployments/firebase/functions
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  FIREBASE_SECRETS_TYPE: ${{ secrets.FIREBASE_SECRETS_TYPE }}
                  FIREBASE_SECRETS_PROJECT_ID: ${{ secrets.FIREBASE_SECRETS_PROJECT_ID }}
                  FIREBASE_SECRETS_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_SECRETS_PRIVATE_KEY_ID }}
                  FIREBASE_SECRETS_PRIVATE_KEY: ${{ secrets.FIREBASE_SECRETS_PRIVATE_KEY }}
                  FIREBASE_SECRETS_CLIENT_EMAIL: ${{ secrets.FIREBASE_SECRETS_CLIENT_EMAIL }}
                  FIREBASE_SECRETS_CLIENT_ID: ${{ secrets.FIREBASE_SECRETS_CLIENT_ID }}
                  FIREBASE_SECRETS_AUTH_URI: ${{ secrets.FIREBASE_SECRETS_AUTH_URI }}
                  FIREBASE_SECRETS_TOKEN_URI: ${{ secrets.FIREBASE_SECRETS_TOKEN_URI }}
                  FIREBASE_SECRETS_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_SECRETS_AUTH_PROVIDER_X509_CERT_URL }}
                  FIREBASE_SECRETS_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_SECRETS_CLIENT_X509_CERT_URL }}
                  FIREBASE_SECRETS_APP_APIKEY: ${{ secrets.FIREBASE_SECRETS_APP_APIKEY }}
                  FIREBASE_SECRETS_APP_AUTHDOMAIN: ${{ secrets.FIREBASE_SECRETS_APP_AUTHDOMAIN }}
                  FIREBASE_SECRETS_APP_DATABASEURL: ${{ secrets.FIREBASE_SECRETS_APP_DATABASEURL }}
                  FIREBASE_SECRETS_APP_STORAGEBUCKET: ${{ secrets.FIREBASE_SECRETS_APP_STORAGEBUCKET }}
                  FIREBASE_SECRETS_APP_MESSAGINGSENDERID: ${{ secrets.FIREBASE_SECRETS_APP_MESSAGINGSENDERID }}
                  FIREBASE_SECRETS_APP_APPID: ${{ secrets.FIREBASE_SECRETS_APP_APPID }}
              run: npm run deploy:ci
