name: Continuous Integration

on: [push]

jobs:
    dispatch_build:
        runs-on: ubuntu-latest
        steps:
            - name: Repository Dispatch
              if: contains(github.event.head_commit.committer.email, 'robotiger@users.noreply.github.com') == false
              uses: peter-evans/repository-dispatch@v1
              with:
                  token: ${{ secrets.PRIVATE_TOKEN }}
                  repository: feuertiger/feuertiger
                  event-type: build
                  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
            - name: Stop gracefully
              if: failure()
