name: Prepare

on: [push]

jobs:
  build_dev_environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: feuertiger-dev-environment
          image-tag: latest
          dockerfile: ./dev-environment/Dockerfile
